spring:
  application:
    name: ai-core-service2
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: ginitoru
    password: 1234
  ai:
    openai:
      api-key: fake_key  ----> see AiConfig.java for configuration
#      embedding:
#        base-url:
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 3072
        max-document-batch-size: 10000
    chat:
      memory:
        repository:
          jdbc:
           #  it initializes the cht memory table only when using spring-data-JPA. Is not working when on the class path is just spring-jdbc dependency.
            initialize-schema: always
            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-postgresql.sql #where we can find the schema for chat memory for postgresql

  #      chat:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#        base-url: http://localhost:11434
#        options:
#          model: gemma3:12b
#          max-tokens: 300000
#          temperature: 0.5


weather:
  key:

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
