services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-postgre-ai
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: ginitoru
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-volume:
