services:
  postgres-wishlist:
    image: postgres
    container_name: postgres-ai
    environment:
      POSTGRES_USER: ginitoru
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aidatabase
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-volume:
